---
- name: Устанавливаем Patroni и зависимости
  pip:
    name:
      - "patroni[etcd]"
      - psycopg2-binary
    state: present

- name: Создаем пользователя patroni
  user:
    name: patroni
    system: yes
    shell: /bin/false

- name: Создаем каталог конфигурации
  file:
    path: /etc/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Копируем конфиг Patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: '0600'

- name: Копируем systemd unit
  copy:
    src: patroni.service
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'

- name: Запускаем Patroni
  systemd:
    daemon_reload: yes
    name: patroni
    enabled: yes
    state: started
